project_name: aws-saml

builds:
  - id: aws-saml
    binary: aws-saml

    targets:
      - darwin_amd64
      - linux_amd64

    flags:
      - -buildvcs=false
      - -trimpath

    ldflags:
      - -s -w
      - -buildid=
      - -X jdk.sh/meta.date={{ .Date }}
      - -X jdk.sh/meta.sha={{ .Commit }}
      - -X jdk.sh/meta.version={{ .Tag }}

    env:
      - CGO_ENABLED=0

    hooks:
      post:
        - upx --best --ultra-brute "{{ .Path }}"

  - id: aws-saml-m1
    binary: aws-saml

    targets:
      - darwin_arm64

    flags:
      - -buildvcs=false
      - -trimpath

    ldflags:
      - -s -w
      - -buildid=
      - -X jdk.sh/meta.date={{ .Date }}
      - -X jdk.sh/meta.sha={{ .Commit }}
      - -X jdk.sh/meta.version={{ .Tag }}

    env:
      - CGO_ENABLED=0

archives:
  - id: aws-saml
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

release:
  name_template: "{{ .Tag }} Release"
  prerelease: auto

checksum:
  name_template: "checksums.txt"

changelog:
  skip: true

brews:
  - name: aws-saml

    tap:
      owner: joshdk
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_GITHUB_TOKEN }}"

    url_template: "https://github.com/joshdk/aws-saml/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    commit_msg_template: "feat: brew formula update for {{ .ProjectName }} {{ .Tag }}"
    commit_author:
      name: Josh Komoroske
      email: jdkomo@gmail.com

    folder: Formula

    caveats: "Run aws-saml --help for usage"
    homepage: "https://github.com/joshdk/aws-saml"
    description: "Generate AWS credentials from a SAML IdP login"
    license: "MIT"

    test: |
      system "#{bin}/aws-saml --version"
