name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Release
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Build and publish release artifacts
        uses: goreleaser/goreleaser-action@v6
        with:
          # https://github.com/goreleaser/goreleaser/releases/tag/v2.9.0
          version: v2.9.0
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_GITHUB_TOKEN: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
